import Fluent
import Vapor

enum ProposeStatus: String, Codable, Sendable {
    case proposed
    case signed
    case honored
    case dissolved
    case parted
}

// Core proposal entity. State transitions are secured by signature verification.
final class Propose: Model, @unchecked Sendable {
    static let schema = "proposes"

    // UUID generated by the client
    @ID(key: .id)
    var id: UUID?

    @Field(key: "content_hash")
    var contentHash: String

    @Field(key: "creator_public_key")
    var creatorPublicKey: String

    @Field(key: "creator_signature")
    var creatorSignature: String

    // Creator's honor/part signatures (counterparty signatures are in ProposeCounterparty)
    @OptionalField(key: "honor_creator_signature")
    var honorCreatorSignature: String?

    @OptionalField(key: "part_creator_signature")
    var partCreatorSignature: String?

    @Field(key: "status")
    var status: String  // Stores the rawValue of ProposeStatus

    // ISO8601 format, generated by the client
    @Field(key: "created_at")
    var createdAt: String

    // Last updated timestamp managed by the server
    @Timestamp(key: "updated_at", on: .update)
    var updatedAt: Date?

    @Children(for: \.$propose)
    var counterparties: [ProposeCounterparty]

    init() { }

    init(
        id: UUID,
        contentHash: String,
        creatorPublicKey: String,
        creatorSignature: String,
        createdAt: String
    ) {
        self.id = id
        self.contentHash = contentHash
        self.creatorPublicKey = creatorPublicKey
        self.creatorSignature = creatorSignature
        self.status = ProposeStatus.proposed.rawValue
        self.createdAt = createdAt
        self.updatedAt = Date()
    }

    var proposeStatus: ProposeStatus {
        get { ProposeStatus(rawValue: status) ?? .proposed }
        set { status = newValue.rawValue }
    }
}
