name: CI

on:
  pull_request:
    branches: [main, "rc-*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  UnitTest:
    uses: ./.github/workflows/unit-test.yml
